AWSTemplateFormatVersion: "2010-09-09"
Resources:
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: glue-etl-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: [glue.amazonaws.com] }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
